### ISSUE TITLE
Sublime Text高亮问题

### ISSUE THREAD

**Issue by iovxw** [sipin/gorazor#27]
![screenshot170](https://cloud.githubusercontent.com/assets/6631572/4268567/7c6cf51c-3cb0-11e4-80b6-cfcd65c0bd0f.png)

如果直接使用'@for'之类的话后面不会高亮

版本为`Sublime Text 3 Build 3065`

未测试`Sublime Text 2`是否有此现象

所有高亮主题都会出现

**Comment by Wuvist** [comment]
sublime 插件不再支持
