### ISSUE TITLE
Not Compatible with idea

### ISSUE THREAD

**Issue by bronze1man** [sipin/gorazor#41]
![image](https://cloud.githubusercontent.com/assets/1107541/7853425/9994fabe-0540-11e5-987b-db9cd68c6313.png)

**Comment by Wuvist** [comment]
too bad. maybe stick to Sublime Text with [GoRazor](https://packagecontrol.io/packages/GoRazor) plug-in?

PS: you may also need to use Sunburst color scheme for sublime to ensure proper syntax highlight.

**Comment by bronze1man** [comment]
It only has this bug,Most of the template is ok.
I think a php like syntax may be better.
