### ISSUE TITLE
Change the file case of the gohtml file,build the go file in mac,push it to a git ,pull that git in linux,and build the go file again,you will get two golang files with file case different.And the package will not compile in linux

### ISSUE THREAD

**Issue by bronze1man** [sipin/gorazor#44]
只修改gohtml文件的大小写,然后在mac里面生成模板,传到git里面.再到linux里面拉取,然后会生成2个大小写不一样的go文件导致无法编译.
Change the file case of the gohtml file,build the go file in mac,push it to a git ,pull that git in linux,and build the go file again,you will get two golang files with file case different.And the package will not compile in linux.

**Comment by Wuvist** [comment]
这是属于git的使用问题，在git中删除多余文件即可。
