### ISSUE TITLE
Import models from main package

### ISSUE THREAD

**Issue by vadimyer** [sipin/gorazor#47]
Hello!

I'm sorry for the silly question, but is it possible to declare model variables from main package? If yes, how could I call it?

The problem is, I want to send an interface with a map like Content{var, var, var, map}
but in the end get "undefined map" error

Also, might be a good idea to add examples of models to examples, I'm missing the model code from your example packages :(

Thanks.

**Comment by vadimyer** [comment]
Already managed to make everything work as intended. Sorry for bothering ;)
Just one question then: is there a way to easily switch off escaping by default, and just use something like @htmlescape(var) ?

**Comment by Wuvist** [comment]
you mean @raw(some_html_string)  ?

**Comment by vadimyer** [comment]
I mean vice versa, *not* escape by default, and do that manually?
