### ISSUE TITLE
gorazor misses performance optimizations.

### ISSUE THREAD

**Issue by iamybj** [sipin/gorazor#60]
I found comparison between quicktemplate and gorazor here: 
https://github.com/valyala/quicktemplate

What's the difference between quicktemplate and gorazor?

Gorazor is similar to quicktemplate in the sense it converts templates into Go code. But it misses the following useful features:

Clear syntax insead of hard-to-understand magic stuff related to template arguments, template inheritance and embedding function templates into other templates.
Performance optimizations.

**Comment by dalu** [comment]
Razor misses clear syntax vs quicktemplate?
I took a look at both and razor seems more intuitive, however not sure if still maintained or how usable it is.

What kind of issues is this? What "performance optimizations"?

Template inheritance are likewise explained in the readme.
Did you bother to read it at all or did you have a "I'll just crap over the repo because I feel like shit today" moment?

**Comment by Wuvist** [comment]
@iamybj razor is an well-known template engine originated from .net, IHMO this go port has very clear syntax, not sure why there is claim about "hard-to-understand magic stuff" etc.

In terms of performance, gorazor didn't pay much attention to it, as codes generated are essentially `_buffer.WriteString`. Nonetheless, according to https://github.com/SlinSo/goTemplateBenchmark gorazor seems about 5x faster than go's builtin template.

**Comment by Wuvist** [comment]
@dalu gorazor is not actively under maintained, but all features stated in readme should be working, personally I had used it in large projects with millions LOC. I will continue to make sure that they continue to work with newest version of go.

But, I don't have plans for new feature or performance optimizations (It's already 5x faster than built-in template) and I feel that the current development trend is to separate frontend from backend. Backend is mainly mean to provide API, usage of HTML rendering is getting more and more limited.

So, while keeping gorazor "alive", I will focus on other projects like http://github.com/yoozoo/protoapi

**Comment by Wuvist** [comment]
@iamybj with the new release of gorazor 2.0, gorazor could be [80%+ faster](https://github.com/sipin/gorazor#performance-comparison-with-htmltemplate-and-quicktemplate) than quicktemplate.
