### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by surfmuggle** [sipin/gorazor#78]
To indicate the status of this project adding a statement like feature complete or work discontinued would be helpfull.

**Comment by Wuvist** [comment]
thank you I've updated the project status as feature complete [2cd1633](https://github.com/sipin/gorazor/commit/2cd16336e1647a7a719801be67a632f43064755e)

I have used gorazor intensively in several projects in production, and it served me well as a good old template engine.

**Comment by surfmuggle** [comment]
@Wuvist thanks for updating the readme. Are you still using razor or have you switched to other libraries (which)?

**Comment by Wuvist** [comment]
@surfmuggle I always use `gorazor` when I need HTML template in go, it serves me well for years.
